# -*- coding: utf-8 -*-
"""Copy of CS335_PythonLab1_Henry_Mendez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ij-gdDqe19KfMpV2AJQdO_n1pkYIKMNg
"""

name = "Henry Mendez"
age = 39
ai_course = True

print("Name:", name)
print("Age in 5 years:", age + 5)
print("Is enrolled in CS 335 course?", ai_course)

topics = ["Logic", "Search", "NLP", "ML", "Bayesian Inference", "Computer Vision", "Reinforcemt Learning"]

for idx, topic in enumerate(topics, start=1):
    print(f"{idx}. {topic}")

student = {"name": "Henry", "score": 95}

if student["score"] >= 95:
    grade = "A+"
elif student["score"] >= 90:
     grade = "A"
elif student["score"] >= 80:
     grade = "B"
else:
     grade = "C or below"

print(f"{student['name']} received a grade of {grade}.")

def greet_student(name):
  return f"Welcome to Omeed, {name}!"

# Test
print(greet_student("Henry"))

def square_number(num):
  """Return the square of num."""
  return num * num

# Test
print(square_number(3))
print(square_number(7))